<?xml version="1.0" encoding="utf-8"?>
<lieferschein>
  <status>{$beleg->status|escapeXml}</status>
  <datum>{$beleg->datum|date_format:'%d.%m.%Y'|escapeXml}</datum>
  <lieferdatum>{$beleg->lieferdatum|escapeXml}</lieferdatum>
  <tatsaechlicheslieferdatum>{$beleg->tatsaechlicheslieferdatum|escapeXml}</tatsaechlicheslieferdatum>
  <versandart>{$beleg->versandart|escapeXml}</versandart>
  <zahlungsweise>{$beleg->zahlungsweise|escapeXml}</zahlungsweise>
  <belegnr>{$beleg->belegnr|escapeXml}</belegnr>
  <hauptbelegnr>{$beleg->hauptbelegnr|escapeXml}</hauptbelegnr>
  <kundennummer>{$beleg->kundennummer|escapeXml}</kundennummer>
  <name>{$beleg->name|escapeXml}</name>
  <abteilung>{$beleg->abteilung|escapeXml}</abteilung>
  <unterabteilung>{$beleg->unterabteilung|escapeXml}</unterabteilung>
  <adresszusatz>{$beleg->adresszusatz|escapeXml}</adresszusatz>
  <ansprechpartner>{$beleg->ansprechpartner|escapeXml}</ansprechpartner>
  <telefon>{$beleg->telefon|escapeXml}</telefon>
  <email>{$beleg->email|escapeXml}</email>
  <land>{$beleg->land|escapeXml}</land>
  <strasse>{$beleg->strasse|escapeXml}</strasse>
  <plz>{$beleg->plz|escapeXml}</plz>
  <ort>{$beleg->ort|escapeXml}</ort>
  <projekt>{$beleg->projekt|escapeXml}</projekt>
  <aktion>{$beleg->aktion|escapeXml}</aktion>
  <internebemerkung>{$beleg->internebemerkung|escapeXml}</internebemerkung>
  <internebezeichnung>{$beleg->internebezeichnung|escapeXml}</internebezeichnung>
  <freitext>{$beleg->freitext|escapeXml}</freitext>
  <ihrebestellnummer>{$beleg->ihrebestellnummer|escapeXml}</ihrebestellnummer>
  <lieferbedingung>{$beleg->lieferbedingung|escapeXml}</lieferbedingung>
  <art>{$beleg->art|escapeXml}</art>
  <positionen>
    {foreach from=$beleg->positionen key=keyrow item=position}{* Positionen *}
      <position>
        <nummer>{$position->nummer|escapeXml}</nummer>
        <bezeichnung>{$position->bezeichnung|escapeXml}</bezeichnung>
        <beschreibung>{$position->beschreibung|escapeXml}</beschreibung>
        <menge>{$position->menge|escapeXml}</menge>
        <preis>{$position->preis|escapeXml}</preis>
        <rabatt>{$position->rabatt|escapeXml}</rabatt>
        <waehrung>{$position->waehrung|escapeXml}</waehrung>
        <lieferdatum>{$position->lieferdatum|escapeXml}</lieferdatum>
        <sort>{$position->sort|escapeXml}</sort>
        <umsatzsteuer>{$position->umsatzsteuer|escapeXml}</umsatzsteuer>
        <einheit>{$position->einheit|escapeXml}</einheit>
        <zolltarifnummer>{$position->zolltarifnummer|escapeXml}</zolltarifnummer>
        <herkunftsland>{$position->herkunftsland|escapeXml}</herkunftsland>
        <artikelnummerkunde>{$position->artikelnummerkunde|escapeXml}</artikelnummerkunde>
        <freifeld1>{$position->freifeld1|escapeXml}</freifeld1>
        <freifeld2>{$position->freifeld2|escapeXml}</freifeld2>
        <freifeld3>{$position->freifeld3|escapeXml}</freifeld3>
        <freifeld4>{$position->freifeld4|escapeXml}</freifeld4>
        <freifeld5>{$position->freifeld5|escapeXml}</freifeld5>
        <freifeld6>{$position->freifeld6|escapeXml}</freifeld6>
        <freifeld7>{$position->freifeld7|escapeXml}</freifeld7>
        <freifeld8>{$position->freifeld8|escapeXml}</freifeld8>
        <freifeld9>{$position->freifeld9|escapeXml}</freifeld9>
        <freifeld10>{$position->freifeld10|escapeXml}</freifeld10>
        <freifeld11>{$position->freifeld11|escapeXml}</freifeld11>
        <freifeld12>{$position->freifeld12|escapeXml}</freifeld12>
        <freifeld13>{$position->freifeld13|escapeXml}</freifeld13>
        <freifeld14>{$position->freifeld14|escapeXml}</freifeld14>
        <freifeld15>{$position->freifeld15|escapeXml}</freifeld15>
        <freifeld16>{$position->freifeld16|escapeXml}</freifeld16>
        <freifeld17>{$position->freifeld17|escapeXml}</freifeld17>
        <freifeld18>{$position->freifeld18|escapeXml}</freifeld18>
        <freifeld19>{$position->freifeld19|escapeXml}</freifeld19>
        <freifeld20>{$position->freifeld20|escapeXml}</freifeld20>
        <freifeld21>{$position->freifeld21|escapeXml}</freifeld21>
        <freifeld22>{$position->freifeld22|escapeXml}</freifeld22>
        <freifeld23>{$position->freifeld23|escapeXml}</freifeld23>
        <freifeld24>{$position->freifeld24|escapeXml}</freifeld24>
        <freifeld25>{$position->freifeld25|escapeXml}</freifeld25>
        <freifeld26>{$position->freifeld26|escapeXml}</freifeld26>
        <freifeld27>{$position->freifeld27|escapeXml}</freifeld27>
        <freifeld28>{$position->freifeld28|escapeXml}</freifeld28>
        <freifeld29>{$position->freifeld29|escapeXml}</freifeld29>
        <freifeld30>{$position->freifeld30|escapeXml}</freifeld30>
        <freifeld31>{$position->freifeld31|escapeXml}</freifeld31>
        <freifeld32>{$position->freifeld32|escapeXml}</freifeld32>
        <freifeld33>{$position->freifeld33|escapeXml}</freifeld33>
        <freifeld34>{$position->freifeld34|escapeXml}</freifeld34>
        <freifeld35>{$position->freifeld35|escapeXml}</freifeld35>
        <freifeld36>{$position->freifeld36|escapeXml}</freifeld36>
        <freifeld37>{$position->freifeld37|escapeXml}</freifeld37>
        <freifeld38>{$position->freifeld38|escapeXml}</freifeld38>
        <freifeld39>{$position->freifeld39|escapeXml}</freifeld39>
        <freifeld40>{$position->freifeld40|escapeXml}</freifeld40>
      </position>
    {/foreach}
  </positionen>
  {if $beleg->versand}
    <tracking>
      {foreach from=$beleg->versand key=keyversand item=tracking}{* Versand *}
        <tracking>{$tracking->tracking|escapeXml}</tracking>
      {/foreach}
    </tracking>
  {/if}
</lieferschein>
